### ISSUE TITLE
Write delays that break yaml syntax

### ISSUE THREAD

**Issue by cutaway** [cutaway/fslogger-yaml#1]
The original fslogger prints to STDOUT and it does not experience any observable delays or failed writes. But, over time in fslogger-yaml (sometime in small captures but always in large captures) experiences incomplete output. 

More than likely this is an issue with the "if/else" condition used to determine where to write output. Here is an example that is used for each of the writes. The original fslogger printed data immediately. fslogger-yaml actually stores some of the data before writing it so that UDP transmissions and file writes are fewer and associated with the section of yaml data being written.

```
    //YAML comments lines start with '#'. Use this for debug and status statements
    snprintf(msg, MAX_DATA,"#fsevents device cloned (fd %d)\n#fslogger ready\n",clonefd);
    // TODO: Make this a function
    if (udp){
        send_packet(msg, strlen(msg));
    } else {
        fprintf(onf,"%s",msg);
    }
```

Here is an example of the good output and then failed outout.
Good output

```
#fsevents device cloned (fd 5)
#fslogger ready
# => received 1495 bytes

---
Event:
 type: FSE_XATTR_MODIFIED
 pid: 1776
 pname: Google Chrome
Details:
 FSE_ARG_STRING:
   len: 90
   string: "/Users/cutaway/Library/Application Support/Google/Chrome/Default/.com.google.Chrome.B7jFa4"
 FSE_ARG_DEV:
   len: 4
   dev: 0x040007 (major 0, minor 262151)
 FSE_ARG_INO:
   len: 4
   ino: 262154
 FSE_ARG_MODE:
   len: 4
   mode: ?-----x---  (0x040008, vnode type VNON)
 FSE_ARG_UID:
   len: 4
   uid: 262155 (?)
 FSE_ARG_GID:
   len: 4
   gid: 524293 (?)
 FSE_ARG_INT64:
   len: 8
   tstamp: 197083164346259
 FSE_ARG_DONE:
   len: 0
   type: 45887
```

Failed output - You can see failure in the following lines:
    `FSE_ARG_INT64Details:`
    `FSE_ARG_INT64# => received 261 bytes`

```

---
Event:
 type: FSE_RENAME
 pid: 1776
 pname: Google Chrome
Details:
 FSE_ARG_STRING:
   len: 191
   string: "/Users/cutaway/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage/28da9c56fde4021055a681112c092453f74d8dd8/BE6FC940-F470-495D-8487-91E654B39DE3/index-dir/temp-index"
 FSE_ARG_DEV:
   len: 4
   dev: 0x040007 (major 0, minor 262151)
 FSE_ARG_INO:
   len: 4
   ino: 262154
 FSE_ARG_MODE:
   len: 4
   mode: ?-----x---  (0x040008, vnode type VNON)
 FSE_ARG_UID:
   len: 4
   uid: 262155 (?)
 FSE_ARG_GID:
   len: 4
   gid: 12779522 (?)
 FSE_ARG_STRING:
   len: 195
   string: "/Users/cutaway/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage/28da9c56fde4021055a681112c092453f74d8dd8/BE6FC940-F470-495D-8487-91E654B39DE3/index-dir/the-real-index"
 FSE_ARG_DEV:
   len: 4
   dev: 0x040007 (major 0, minor 262151)
 FSE_ARG_INO:
   len: 4
   ino: 262154
 FSE_ARG_MODE:
   len: 4
   mode: ?-----x---  (0x040008, vnode type VNON)
 FSE_ARG_UID:
   len: 4
   uid: 262155 (?)
 FSE_ARG_GID:
   len: 4
   gid: 524293 (?)
 FSE_ARG_INT64Details:
 FSE_ARG_STRING:
   len: 191
   string: "/Users/cutaway/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage/28da9c56fde4021055a681112c092453f74d8dd8/BE6FC940-F470-495D-8487-91E654B39DE3/index-dir/temp-index"
 FSE_ARG_DEV:
   len: 4
   dev: 0x040007 (major 0, minor 262151)
 FSE_ARG_INO:
   len: 4
   ino: 262154
 FSE_ARG_MODE:
   len: 4
   mode: ?-----x---  (0x040008, vnode type VNON)
 FSE_ARG_UID:
   len: 4
   uid: 262155 (?)
 FSE_ARG_GID:
   len: 4
   gid: 12779522 (?)
 FSE_ARG_STRING:
   len: 195
   string: "/Users/cutaway/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage/28da9c56fde4021055a681112c092453f74d8dd8/BE6FC940-F470-495D-8487-91E654B39DE3/index-dir/the-real-index"
 FSE_ARG_DEV:
   len: 4
   dev: 0x040007 (major 0, minor 262151)
 FSE_ARG_INO:
   len: 4
   ino: 262154
 FSE_ARG_MODE:
   len: 4
   mode: ?-----x---  (0x040008, vnode type VNON)
 FSE_ARG_UID:
   len: 4
   uid: 262155 (?)
 FSE_ARG_GID:
   len: 4
   gid: 524293 (?)
 FSE_ARG_INT64# => received 261 bytes

---
Event:
```
